In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

mpg_df = sns.load_dataset('mpg')

In [6]:
pipe_horsepower = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ]
)

pipe_horsepower

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [9]:
pipe_horsepower.fit(mpg_df[['horsepower']])
pipe_horsepower


Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [12]:
pipe_horsepower['scaler'].mean_

array([104.3040201])

In [14]:
pipe_horsepower['scaler'].n_samples_seen_

np.int64(398)

In [17]:
transformer_numeric = ColumnTransformer(
transformers = [
 ('with_nan', pipe_horsepower, ["horsepower"]),
     ('without_nan', StandardScaler(), ["mpg", "displacement","weight", "acceleration"]),
], # el resto por default se va a drop
   # remainder="passthrough"
)
transformer_numeric

ColumnTransformer(transformers=[('with_nan',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['horsepower']),
                                ('without_nan', StandardScaler(),
                                 ['mpg', 'displacement', 'weight',
                                  'acceleration'])])

In [18]:
transformer_numeric.fit_transform(mpg_df)

array([[ 0.67311762, -0.7064387 ,  1.0906037 ,  0.63086987, -1.29549834],
       [ 1.58995818, -1.09075062,  1.5035143 ,  0.85433297, -1.47703779],
       [ 1.19702651, -0.7064387 ,  1.19623199,  0.55047045, -1.65857724],
       ...,
       [-0.53187283,  1.08701694, -0.56103873, -0.79858454, -1.4407299 ],
       [-0.66285006,  0.57460104, -0.70507731, -0.40841088,  1.10082237],
       [-0.58426372,  0.95891297, -0.71467988, -0.29608816,  1.39128549]],
      shape=(398, 5))

In [21]:
# vamos a crear otro mas grande
preprocessor =ColumnTransformer(
transformers = [
     ('numeric_with_nan', pipe_horsepower, ["horsepower"]),
     ('numeric_without_nan', StandardScaler(), ["mpg", "displacement","weight", "acceleration"]),
     ('categorical_ordinal', OrdinalEncoder(categories="auto"), ["cylinders", "model_year"]),
     ('categorical_nominal', OneHotEncoder(categories="auto", handle_unknown='error'), ["origin", "name"]),
],
remainder='drop'
)
preprocessor

ColumnTransformer(transformers=[('numeric_with_nan',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['horsepower']),
                                ('numeric_without_nan', StandardScaler(),
                                 ['mpg', 'displacement', 'weight',
                                  'acceleration']),
                                ('categorical_ordinal', OrdinalEncoder(),
                                 ['cylinders', 'model_year']),
                                ('categorical_nominal', OneHotEncoder(),
                                 ['origin', 'name'])])

In [23]:
preprocessor.fit_transform(mpg_df).toarray()

array([[ 0.67311762, -0.7064387 ,  1.0906037 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.58995818, -1.09075062,  1.5035143 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.19702651, -0.7064387 ,  1.19623199, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.53187283,  1.08701694, -0.56103873, ...,  0.        ,
         0.        ,  0.        ],
       [-0.66285006,  0.57460104, -0.70507731, ...,  0.        ,
         0.        ,  0.        ],
       [-0.58426372,  0.95891297, -0.71467988, ...,  0.        ,
         0.        ,  0.        ]], shape=(398, 315))

In [25]:
pipe = Pipeline(steps=[
    ("preprocessor",preprocessor)
])

pipe.fit_transform(mpg_df).toarray()

array([[ 0.67311762, -0.7064387 ,  1.0906037 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.58995818, -1.09075062,  1.5035143 , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.19702651, -0.7064387 ,  1.19623199, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.53187283,  1.08701694, -0.56103873, ...,  0.        ,
         0.        ,  0.        ],
       [-0.66285006,  0.57460104, -0.70507731, ...,  0.        ,
         0.        ,  0.        ],
       [-0.58426372,  0.95891297, -0.71467988, ...,  0.        ,
         0.        ,  0.        ]], shape=(398, 315))

In [26]:
# DataFrame amb el nombs de les comlumnes
resultat = pd.DataFrame(pipe.fit_transform(mpg_df).toarray())
resultat

0         1         2         3         4    5     6    7    8    ...  306  307  308  309  310  311  312  313  314
0    0.673118 -0.706439  1.090604  0.630870 -1.295498  4.0   0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1    1.589958 -1.090751  1.503514  0.854333 -1.477038  4.0   0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2    1.197027 -0.706439  1.196232  0.550470 -1.658577  4.0   0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3    1.197027 -0.962647  1.061796  0.546923 -1.295498  4.0   0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4    0.935072 -0.834543  1.042591  0.565841 -1.840117  4.0   0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
..        ...       ...       ...       ...       ...  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
393 -0.479482  0.446497 -0.513026 -0.213324  0.011586  1.0  12.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
394 -1.370127  2.624265 -0.925936 -0.993671  3.279296  1.0  12.0  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
395 -0.531873  1.087017 -0.561039 -0.798585 -1.440730  1.0  12.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
396 -0.662850  0.574601 -0.705077 -0.408411  1.100822  1.0  12.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
397 -0.584264  0.958913 -0.714680 -0.296088  1.391285  1.0  12.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[398 rows x 315 columns]

In [31]:
# lo siguietne es ponerle nombre a las columnas segun lo haya visto 
pipe['preprocessor']["categorical_nominal"].get_feature_names_out() # asi accedo al categorical_nominal y desde ahi puedo obtener los nomber del categorical nominal que crea una columna por valro



array(['origin_europe', 'origin_japan', 'origin_usa',
       'name_amc ambassador brougham', 'name_amc ambassador dpl',
       'name_amc ambassador sst', 'name_amc concord',
       'name_amc concord d/l', 'name_amc concord dl',
       'name_amc concord dl 6', 'name_amc gremlin', 'name_amc hornet',
       'name_amc hornet sportabout (sw)', 'name_amc matador',
       'name_amc matador (sw)', 'name_amc pacer', 'name_amc pacer d/l',
       'name_amc rebel sst', 'name_amc spirit dl', 'name_audi 100 ls',
       'name_audi 100ls', 'name_audi 4000', 'name_audi 5000',
       'name_audi 5000s (diesel)', 'name_audi fox', 'name_bmw 2002',
       'name_bmw 320i', 'name_buick century', 'name_buick century 350',
       'name_buick century limited', 'name_buick century luxus (sw)',
       'name_buick century special', 'name_buick electra 225 custom',
       'name_buick estate wagon (sw)', 'name_buick lesabre custom',
       'name_buick opel isuzu deluxe',
       'name_buick regal sport coupe (turbo)',

In [32]:
# ponemos la lista en orden
columnes =['horsepower',"mpg", "displacement","weight", "acceleration"]
columnes = np.append(columnes, ["cylinders", "model_year"])
columnes = np.append(columnes, pipe['preprocessor']["categorical_nominal"].get_feature_names_out())
columnes

array(['horsepower', 'mpg', 'displacement', 'weight', 'acceleration',
       'cylinders', 'model_year', 'origin_europe', 'origin_japan',
       'origin_usa', 'name_amc ambassador brougham',
       'name_amc ambassador dpl', 'name_amc ambassador sst',
       'name_amc concord', 'name_amc concord d/l', 'name_amc concord dl',
       'name_amc concord dl 6', 'name_amc gremlin', 'name_amc hornet',
       'name_amc hornet sportabout (sw)', 'name_amc matador',
       'name_amc matador (sw)', 'name_amc pacer', 'name_amc pacer d/l',
       'name_amc rebel sst', 'name_amc spirit dl', 'name_audi 100 ls',
       'name_audi 100ls', 'name_audi 4000', 'name_audi 5000',
       'name_audi 5000s (diesel)', 'name_audi fox', 'name_bmw 2002',
       'name_bmw 320i', 'name_buick century', 'name_buick century 350',
       'name_buick century limited', 'name_buick century luxus (sw)',
       'name_buick century special', 'name_buick electra 225 custom',
       'name_buick estate wagon (sw)', 'name_buick lesab

In [33]:
resultat.columns = columnes
resultat

horsepower       mpg  displacement  ...  name_vw rabbit  name_vw rabbit c (diesel)  name_vw rabbit custom
0      0.673118 -0.706439      1.090604  ...             0.0                        0.0                    0.0
1      1.589958 -1.090751      1.503514  ...             0.0                        0.0                    0.0
2      1.197027 -0.706439      1.196232  ...             0.0                        0.0                    0.0
3      1.197027 -0.962647      1.061796  ...             0.0                        0.0                    0.0
4      0.935072 -0.834543      1.042591  ...             0.0                        0.0                    0.0
..          ...       ...           ...  ...             ...                        ...                    ...
393   -0.479482  0.446497     -0.513026  ...             0.0                        0.0                    0.0
394   -1.370127  2.624265     -0.925936  ...             0.0                        0.0                    0.0
395   -0.531873  1.087017     -0.561039  ...             0.0                        0.0                    0.0
396   -0.662850  0.574601     -0.705077  ...             0.0                        0.0                    0.0
397   -0.584264  0.958913     -0.714680  ...             0.0                        0.0                    0.0

[398 rows x 315 columns]